# Change these first
owner: 0xdhrv # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Week Flow
    url: https://wf.dhrv.pw
  - name: Dhruv Portfolio
    url: https://dhrv.pw

assignees:
  - 0xdhrv


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime/
  customThemeCss: https://raw.githubusercontent.com/0xdhrv/uptime/master/assets/radix-theme.css
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/19857414?v=4
  name: Dhruv Suthar
  introTitle: "uptime"
  introMessage: "uptime monitoring for Dhruv's services"
  links:
    - rel: stylesheet
      href: https://cdn-bi1.pages.dev/sans.css
  css: "body { font-family: 'D', sans-serif; }"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
